services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./web-app:/web-app
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./web-app:/web-app
    links:
      - redis
    depends_on:
      - redis

  react-web-app:
    build:
      context: ./react-web-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-web-app:/react-web-app

    command: >
      sh -c "npm start 0.0.0.0:3000"